version: '1.0'

services:
  build:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        ANCHOR_CLI: v0.30.1
        SOLANA_CLI: v2.1.0
    volumes:
      - .:/workdir
    working_dir: /workdir
    network_mode: "host"
    command: /bin/bash -c "cd ../tmp/dummy && anchor build"   #compile

  validator:
    image: backpackapp/build:v0.30.1
    command: solana-test-validator --reset
    volumes:
      - .:/workdir
    working_dir: /workdir
    network_mode: "host"
    ports:
      - "8899:8899"
      - "8900:8900"

  deploy:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        ANCHOR_CLI: v0.30.1
        SOLANA_CLI: v2.1.0
    volumes:
      - .:/workdir
    working_dir: /workdir
    network_mode: "host"
    command:  > 
      /bin/bash -c "
      if [ ! -f /root/.config/solana/id.json ]; then
      echo 'Keypair not found. Generating a new one...';
      mkdir -p /root/.config/solana &&
      solana-keygen new --outfile /root/.config/solana/id.json --no-bip39-passphrase &&
      solana config set --url http://127.0.0.1:8899 &&
      solana airdrop 2;
      fi &&
      cd /tmp/dummy && anchor deploy
      "

  test:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        ANCHOR_CLI: v0.30.1
        SOLANA_CLI: v2.1.0
    volumes:
      - .:/workdir
    working_dir: /workdir
    network_mode: "host"
    command: /bin/bash -c "cd ../tmp/dummy && anchor test"  # Runs anchor test

  keys-sync:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        ANCHOR_CLI: v0.30.1
        SOLANA_CLI: v2.1.0
    volumes:
      - .:/workdir
    working_dir: /workdir
    network_mode: "host"
    command: /bin/bash -c "cd ../tmp/dummy && anchor keys sync"  # Runs anchor keys sync

  load-account:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        ANCHOR_CLI: v0.30.1
        SOLANA_CLI: v2.1.0
    volumes:
      - .:/workdir
    working_dir: /workdir
    network_mode: "host"
    command: /bin/bash -c "load-account.sh <account_address>"

  anchor-version:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        ANCHOR_CLI: v0.30.1
        SOLANA_CLI: v2.1.0
    volumes:
      - .:/workdir
    working_dir: /workdir
    network_mode: "host"
    command: /bin/bash -c "anchor-version.sh <version>"

  create-dapp:
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - .:/workdir
    working_dir: /workdir
    network_mode: "host"
    command: /bin/bash -c "create-dapp.sh <project_name>"
